=== dantleech/cmf-content-type/schema/mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://github.com/psiphp/content-type/mapping"
    xmlns:psi="http://github.com/psiphp/content-type/mapping"
    elementFormDefault="qualified">

    <xs:annotation>
        <xs:documentation><![CDATA[
            This is the XML schema for the class mappings
            for the Psi Content Type component.
            ]]></xs:documentation>
    </xs:annotation>

    <xs:element name="content-type-mapping">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="class" type="psi:class" minOccurs="1" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="class">
        <xs:sequence>
            <xs:element name="field" type="psi:field" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="field">
        <xs:sequence>
            <xs:element name="shared-options" type="psi:option-set" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="form-options" type="psi:option-set" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="view-options" type="psi:option-set" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="storage-options" type="psi:option-set" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="type" type="xs:string" use="required" />
        <xs:attribute name="role" type="xs:string" />
        <xs:attribute name="group" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="option" mixed="true">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="option" type="psi:option"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="psi:option_type" />
    </xs:complexType>

    <xs:complexType name="option-set">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="option" type="psi:option"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="option_type">
        <xs:restriction base="xs:token">
            <xs:enumeration value="collection"/>
            <xs:enumeration value="scalar"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== dantleech/cmf-content-type/tests/Unit/Metadata/Driver/xml/Example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<content-type-mapping
    xmlns="http://github.com/psiphp/content-type/mapping"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://github.com/psiphp/content-type
    https://github.com/psiphp/content-type/raw/master/schema/mapping.xsd"
    >

    <class
        name="Psi\Component\ContentType\Tests\Unit\Metadata\Driver\Model\Example"
        >

        <field name="fieldOne" type="markdown" role="title" group="group_one">
            <option name="option_one">Foobar</option>
            <option name="option_two">Barfoo</option>
            <option name="option_three" type="collection">
                <option name="sub_one">One</option>
                <option name="sub_two">Two</option>
            </option>
        </field>

        <field name="fieldTwo" type="date">
            <option name="option_one">Foobar</option>
            <option name="option_two">Barfoo</option>
        </field>

    </class>

</content-type-mapping>
